# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  lint:
    docker:
    - image: trikset/linux-builder
    steps:
    - checkout
    - run: buildScripts/travis/vera_translation.sh
  build:
    docker:
    - image: trikset/linux-builder
    steps:
    - checkout
    - run: buildScripts/travis/script.sh

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  main:
    jobs:
      - lint
      - build:
          requires:
            - lint
        #      - test:
        #        requires:
        #        - build


